In [2]:
import pandas as pd
import numpy as np

In [6]:
flats_df=pd.read_csv('/content/flats_cleaned .csv')
house_df=pd.read_csv('/content/house_cleaned.csv')

In [8]:
flats_df['property_type']='flat'
house_df['property_type']='house'

In [9]:
flats_df.head()

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,floor,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type
0,3 Bed Drawing Dining Flat Is For Sale,"tariq road, karachi",tariq road,65000000.0,1800.0,3,4,1.0,NaN,NaN,1,0,0,0,0,2023.0,flat
1,3b-2 Bedrooms full sea facing of Panorama towe...,"emaar panorama, dha phase 8",dha defence,130000000.0,2700.0,3,4,2.0,NaN,45.0,2,4,1,1,0,2026.0,flat
2,2000 Square Feet Spacious 3 Bedroom Apartment ...,"dha phase 6, dha defence",dha defence,55000000.0,1998.0,3,4,1.0,NaN,NaN,0,0,0,0,0,NaN,flat
3,ULTRA-LUXURY COASTAL INVESTMENT: EXPANSIVE 3-B...,"emaar park edge, dha phase 8",dha defence,143500000.0,2700.0,3,3,1.0,NaN,NaN,0,1,0,0,1,NaN,flat
4,Prime Location WEST OPEN CHANCE DEAL IDEAL FLO...,"askari 6, malir cantonment",cantt,39000000.0,2997.0,4,4,3.0,1.0,3.0,6,2,1,1,1,2026.0,flat

In [10]:
house_df.head()

,property_name,address,location,price,area,bedrooms,bathrooms,kitchen,total_floors,parking,elevator,servant_quarters,electricity_backup,furnished,completion_year,property_type
0,Prime Location 3Bed DDL 125sq Yd Villa FOR SAL...,"bahria town - ali block, bahria town - precinc...",bahria town karachi,14500000.0,1125.0,3,3,1.0,2.0,1.0,0,1,1,1,2025.0,house
1,500 SQ YD Brand New 5-Bedroom Villa For Sale P...,"bahria paradise, bahria town karachi",bahria town karachi,46000000.0,4500.0,5,5,2.0,NaN,1.0,0,1,1,0,NaN,house
2,Prime Location 250 Square Yards Modern Design ...,"bahria town - precinct 1, bahria town karachi",bahria town karachi,29000000.0,2250.0,5,5,1.0,NaN,1.0,0,1,1,0,2025.0,house
3,Construct Your 272 Sq. Yds Dream House on Easy...,"bahria town - precinct 6, bahria town karachi",bahria town karachi,24000000.0,2250.0,5,5,1.0,NaN,1.0,0,1,1,0,NaN,house
4,Bungalow for Sale 1000 Square yards in DHA pha...,"dha phase 6, dha defence",dha defence,450000000.0,9000.0,6,7,0.0,2.0,4.0,0,0,1,0,2024.0,house

In [11]:
df = pd.concat([flats_df,house_df],ignore_index=True)

In [14]:
df = df.sample(df.shape[0],ignore_index=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22888 entries, 0 to 22887
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   property_name       22888 non-null  object
 1   address             22888 non-null  object
 2   location            22888 non-null  object
 3   price               22888 non-null  float64
 4   area                22888 non-null  float64
 5   bedrooms            22888 non-null  int64
 6   bathrooms           22888 non-null  int64
 7   kitchen             22855 non-null  float64
 8   floor               3710 non-null   float64
 9   total_floors        9526 non-null   float64
 10  parking             22847 non-null  float64
 11  elevator            22888 non-null  int64
 12  servant_quarters    22888 non-null  int64
 13  electricity_backup  22888 non-null  int64
 14  furnished           22888 non-null  int64
 15  completion_year     11559 non-null  float64
 16  property_type       22888 non-null  object
dtypes: float64(7), int64(6), object(4)
memory usage: 3.0+ MB

In [17]:
df.to_csv('karachi_properties.csv',index=False)